config/routes.rb
Rails.application.routes.draw do
  resources :bookstatuses
  resources :books
  resources :studentsregistereds
  resources :registeredstudents
  resources :students
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/bookstatuses_controller.rb
class BookstatusesController < ApplicationController
  before_action :set_bookstatus, only: %i[ show edit update destroy ]

  # GET /bookstatuses or /bookstatuses.json
  def index
    @bookstatuses = Bookstatus.all
  end

  # GET /bookstatuses/1 or /bookstatuses/1.json
  def show
  end

  # GET /bookstatuses/new
  def new
    @bookstatus = Bookstatus.new
  end

  # GET /bookstatuses/1/edit
  def edit
  end

  # POST /bookstatuses or /bookstatuses.json
  def create
    @bookstatus = Bookstatus.new(bookstatus_params)

    respond_to do |format|
      if @bookstatus.save
        format.html { redirect_to @bookstatus, notice: "Bookstatus was successfully created." }
        format.json { render :show, status: :created, location: @bookstatus }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookstatus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookstatuses/1 or /bookstatuses/1.json
  def update
    respond_to do |format|
      if @bookstatus.update(bookstatus_params)
        format.html { redirect_to @bookstatus, notice: "Bookstatus was successfully updated." }
        format.json { render :show, status: :ok, location: @bookstatus }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookstatus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookstatuses/1 or /bookstatuses/1.json
  def destroy
    @bookstatus.destroy
    respond_to do |format|
      format.html { redirect_to bookstatuses_url, notice: "Bookstatus was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookstatus
      @bookstatus = Bookstatus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookstatus_params
      params.require(:bookstatus).permit(:book_name, :available)
    end
end

app/helpers/bookstatuses_helper.rb
module BookstatusesHelper
end

app/views/bookstatuses/_form.html.erb
<%= form_with(model: bookstatus) do |form| %>
  <% if bookstatus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookstatus.errors.count, "error") %> prohibited this bookstatus from being saved:</h2>

      <ul>
        <% bookstatus.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :book_name %>
    <%= form.text_field :book_name %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.text_field :available %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookstatuses/edit.html.erb
<h1>Editing Bookstatus</h1>

<%= render 'form', bookstatus: @bookstatus %>

<%= link_to 'Show', @bookstatus %> |
<%= link_to 'Back', bookstatuses_path %>

app/views/bookstatuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookstatuses</h1>

<table>
  <thead>
    <tr>
      <th>Book name</th>
      <th>Available</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookstatuses.each do |bookstatus| %>
      <tr>
        <td><%= bookstatus.book_name %></td>
        <td><%= bookstatus.available %></td>
        <td><%= link_to 'Show', bookstatus %></td>
        <td><%= link_to 'Edit', edit_bookstatus_path(bookstatus) %></td>
        <td><%= link_to 'Destroy', bookstatus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookstatus', new_bookstatus_path %>

app/views/bookstatuses/new.html.erb
<h1>New Bookstatus</h1>

<%= render 'form', bookstatus: @bookstatus %>

<%= link_to 'Back', bookstatuses_path %>

app/views/bookstatuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book name:</strong>
  <%= @bookstatus.book_name %>
</p>

<p>
  <strong>Available:</strong>
  <%= @bookstatus.available %>
</p>

<%= link_to 'Edit', edit_bookstatus_path(@bookstatus) %> |
<%= link_to 'Back', bookstatuses_path %>