config/routes.rb
Rails.application.routes.draw do
  resources :bookstatuses
  resources :books
  resources :studentsregistereds
  resources :registeredstudents
  resources :students
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link disabled" aria-disable="page" href="#">TOC'H INSTITUTE OF SCIENCE AND TECHNOLOGY, Arrakunnam</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Library Webapp</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Contact Number- 0xxxx0kk</a>
  </li>
  <li class="nav-item">
    <a class="nav-link " href="#" tabindex="-1" aria="true">Tist@fffg.com</a>
  </li>
</ul>





<nav class="navbar navbar-expand-lg navbar-drak bg-dark">
  <%= link_to "Tist library Home", root_path, class:"nav-link" %>
  <div class="container-fluid">
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        
        <li class="nav-item">
          <%= link_to "Book List", home_about_path, class:"nav-link" %>
          
        </li>
        
          <%= link_to "Books Availed", bookstatuses_path, class:"nav-link" %>
        
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "Students List", studentsregistereds_path, class:"nav-link" %>
          
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>All Book list</h1>


<h3>1)Fire and Blood-</h3> 

   Fire & Blood is a fantasy book by American writer George R. R. Martin. It tells the history of House Targaryen, a family from his series A Song of Ice and Fire


<h3>2) Wings of Fire-</h3>

    An Autobiography of APJ Abdul Kalam (1999), former President of India. It was written by Dr. Abdul Kalam and Arun Tiwari.
   Dr. Kalam examines his early life, effort, hardship, fortitude, luck and chance that eventually led him to lead Indian space research, nuclear and missile programs. Kalam started his career, after graduating from Aerospace engineering at MIT (Chennai), India, at Hindustan Aeronautics Limited and was assigned to build a hovercraft prototype



<h3>3) Inferno-</h3>

    Inferno is a 2013 mystery thriller novel by American author Dan Brown and the fourth book in his Robert Langdon series, following Angels & Demons, The Da Vinci Code and The Lost Symbol.




<h3>4)Da Vinci Code-</h3>
       
       2003 mystery thriller novel by Dan Brown. It is Brown's second novel to include the character Robert Langdon: the first was his 2000 novel Angels & Demons. The Da Vinci Code follows "symbologist" Robert Langdon and cryptologist Sophie Neveu after a murder in the Louvre Museum in Paris causes them to become involved in a battle between the Priory of Sion and Opus Dei over the possibility of Jesus Christ and Mary Magdalene having had a child together.




<h3>5) The Alchemist-</h3>
    
    The Alchemist (Portuguese: O Alquimista) is a novel by Brazilian author Paulo Coelho that was first published in 1988. Originally written in Portuguese, it became a widely translated international bestseller. An allegorical novel, The Alchemist follows a young Andalusian shepherd in his journey to the pyramids of Egypt, after having a recurring dream of finding a treasure there.




<h3>6) The lost Symbol-</h3>

   The Lost Symbol is a 2009 novel written by American writer Dan Brown. It is a thriller set in Washington, D.C., after the events of The Da Vinci Code, and relies on Freemasonry for both its recurring theme and its major characters




 <h3>7) Poverty in India- V. M. Dandekar (Author), Nilakantha Rath (Author)-</h3>

   This study is concerned with the problem of poverty in India. It is a problem of low national income and its unequal distribution; of slow pace of development and inequitable distribution of the small gains of development.
 



 <h3>8)Indian Polity - For Civil Services and Other State Examinations | 6th Edition Paperback – 27 December 2019-</h3> 

    The book "Indian Polity", 6th edition is a must-read for the aspirants appearing for the Civil Services Examinations as well as the other state Services Examinations. It is conceived to cater to the requirements of not just students appearing for competitive examinations but also postgraduates, research scholars, academics and General readers who are interested in the country political




 <h3> 9)Indian Art and Culture for Civil Services and other Competitive Examinations-</h3>
  
    McGraw-Hill is proud to present third edition of their bestseller “Indian art and Culture” by Nitin Singhania, third edition. This book offers comprehensive and latest information covering the broad field of knowledge on Indian art, paintings, music and architecture for the aspirants of Civil Services Preliminary and Main Examinations.




  <h3>10) Indian Economy Paperback-</h3>



    This book will take your UPSC CSE preparation to the next level. The Indian economy by Aman Soni is a classic case of an integrated approach of understanding the fundamentals of economy and applying them in the current economic events that affects India.   

app/views/home/index.html.erb
<h1>Welcome to Tist library website</h1>

TIST is approved by the All India Council for Technical Education (AICTE), New Delhi and the Government of Kerala and is affiliated to APJ Abdul Kalam Technological University. The college is accredited by the National Assessment and Accreditation Council (NAAC). It is one among the 16 Engineering colleges in Kerala with National Board of Accreditation (NBA) Accredited Programs in Civil Engineering, Computer Science & Engineering, Electronics & Communications Engineering & Mechanical Engineering, under the self financing category.


<h1>Motto:	We want ordinary people to do extra ordinary things.</h1>


<h2>TIST offers B Tech courses in the following disciplines:</h2>

<h3>Mechanical Engineering</h3>
<h3>Electronics and Communication Engineering</h3>
<h3>Computer Science and Engineering</h3>
<h3>Information Technology</h3>
<h3>Electrical and Electronics Engineering</h3>
<h3>Civil Engineering</h3>
<h3>Safety & Fire Engineering</h3>
<h3>Robotics & Automation</h3>

<h2>This institution offers MBA and M.Tech. Offered M.Tech courses are:</h2>

<h3>Thermal Engineering</h3>
<h3>VLSI & Embedded Systems</h3>
<h3>Wireless Technology</h3>
<h3>Power Electronics</h3>
<h3>Computer Science with Specialization in Data Security.</h3>
<h3>Construction Engineering & Management</h3>
<h3>Network Computing</h3>