config/routes.rb
Rails.application.routes.draw do
  resources :bookstatuses
  resources :books
  resources :studentsregistereds
  resources :registeredstudents
  resources :students
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/studentsregistered.rb
class Studentsregistered < ApplicationRecord
end

app/controllers/studentsregistereds_controller.rb
class StudentsregisteredsController < ApplicationController
  before_action :set_studentsregistered, only: %i[ show edit update destroy ]

  # GET /studentsregistereds or /studentsregistereds.json
  def index
    @studentsregistereds = Studentsregistered.all
  end

  # GET /studentsregistereds/1 or /studentsregistereds/1.json
  def show
  end

  # GET /studentsregistereds/new
  def new
    @studentsregistered = Studentsregistered.new
  end

  # GET /studentsregistereds/1/edit
  def edit
  end

  # POST /studentsregistereds or /studentsregistereds.json
  def create
    @studentsregistered = Studentsregistered.new(studentsregistered_params)

    respond_to do |format|
      if @studentsregistered.save
        format.html { redirect_to @studentsregistered, notice: "Studentsregistered was successfully created." }
        format.json { render :show, status: :created, location: @studentsregistered }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @studentsregistered.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studentsregistereds/1 or /studentsregistereds/1.json
  def update
    respond_to do |format|
      if @studentsregistered.update(studentsregistered_params)
        format.html { redirect_to @studentsregistered, notice: "Studentsregistered was successfully updated." }
        format.json { render :show, status: :ok, location: @studentsregistered }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @studentsregistered.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studentsregistereds/1 or /studentsregistereds/1.json
  def destroy
    @studentsregistered.destroy
    respond_to do |format|
      format.html { redirect_to studentsregistereds_url, notice: "Studentsregistered was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studentsregistered
      @studentsregistered = Studentsregistered.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def studentsregistered_params
      params.require(:studentsregistered).permit(:first_name, :last_name, :branch, :contact, :book_availed, :exceeded_duration)
    end
end

app/helpers/studentsregistereds_helper.rb
module StudentsregisteredsHelper
end

app/views/studentsregistereds/_form.html.erb
<%= form_with(model: studentsregistered) do |form| %>
  <% if studentsregistered.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(studentsregistered.errors.count, "error") %> prohibited this studentsregistered from being saved:</h2>

      <ul>
        <% studentsregistered.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :branch %>
    <%= form.text_field :branch %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact %>
  </div>

  <div class="field">
    <%= form.label :book_availed %>
    <%= form.text_field :book_availed %>
  </div>

  <div class="field">
    <%= form.label :exceeded_duration %>
    <%= form.text_field :exceeded_duration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/studentsregistereds/edit.html.erb
<h1>Editing Studentsregistered</h1>

<%= render 'form', studentsregistered: @studentsregistered %>

<%= link_to 'Show', @studentsregistered %> |
<%= link_to 'Back', studentsregistereds_path %>

app/views/studentsregistereds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Studentsregistereds</h1>

<table class="table table-dark table-striped <table class table table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Branch</th>
      <th>Contact</th>
      <th>Book availed</th>
      <th>Exceeded duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @studentsregistereds.each do |studentsregistered| %>
      <tr>
        <td><%= studentsregistered.first_name %></td>
        <td><%= studentsregistered.last_name %></td>
        <td><%= studentsregistered.branch %></td>
        <td><%= studentsregistered.contact %></td>
        <td><%= studentsregistered.book_availed %></td>
        <td><%= studentsregistered.exceeded_duration %></td>
        <td><%= link_to 'Show', studentsregistered %></td>
        <td><%= link_to 'Edit', edit_studentsregistered_path(studentsregistered) %></td>
        <td><%= link_to 'Destroy', studentsregistered, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Studentsregistered', new_studentsregistered_path, class:"btn btn-secondary" %>

app/views/studentsregistereds/new.html.erb
<h1>New Studentsregistered</h1>

<%= render 'form', studentsregistered: @studentsregistered %>

<%= link_to 'Back', studentsregistereds_path %>

app/views/studentsregistereds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @studentsregistered.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @studentsregistered.last_name %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @studentsregistered.branch %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @studentsregistered.contact %>
</p>

<p>
  <strong>Book availed:</strong>
  <%= @studentsregistered.book_availed %>
</p>

<p>
  <strong>Exceeded duration:</strong>
  <%= @studentsregistered.exceeded_duration %>
</p>

<%= link_to 'Edit', edit_studentsregistered_path(@studentsregistered), class:"btn btn-secondary" %> 
<%= link_to 'Back', studentsregistereds_path, class:"btn btn-dark" %>